version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myrent
      MONGO_INITDB_ROOT_PASSWORD: myrent123
    ports:
      - 27017:27017
    volumes:
      - myrent-db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myrent
      ME_CONFIG_MONGODB_ADMINPASSWORD: myrent123
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  myrent-db:
